version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    restart: on-failure
    container_name: client
  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./auth-server:/app
    ports:
      - '3001:3001'
    restart: on-failure
    container_name: auth-server
  nginx: 
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - client
      - auth-server